### ISSUE TITLE
[FEATURE] Use file-scoped namespace on sample code

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/ai-dev-gallery#25]
**Is your feature request related to a problem? Please describe.**

**Sample.xaml.cs** uses **block-scoped namespace** slightly losing a bit of readability, also losing consistency because **GenAIModel.cs** uses **file-scoped namespace**.

![Image](https://github.com/user-attachments/assets/224d3ec9-beef-47d0-9b80-80a86b8550c5)

![Image](https://github.com/user-attachments/assets/d466c263-eeae-4790-833e-ed8866705732)

**Describe the solution you'd like**

It'd be better **Sample.xaml.cs** uses **file-scoped namespace**.

![Image](https://github.com/user-attachments/assets/700fcb15-78a4-474d-a2ff-cf3ebb06e947)

**Describe alternatives you've considered**

**Additional context**

There are other sample code that also uses **block-scoped namespace**.

**Comment by AndrewKeepCoding** [comment]
I could create a PR for these sample code.

**Comment by nmetulev** [comment]
Thanks Andrew - please feel free to submit a PR and update the samples - this is a good suggestion - thank you
