### ISSUE TITLE
[BUG] App crashes when closed during GenAIModel initialization

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/ai-dev-gallery#29]
**Describe the bug**
It takes a few seconds to instantiate `Model`. The app crashes if you close the app.

**GenAIModel.cs**
```cs
private Task InitializeAsync(string modelDir, CancellationToken cancellationToken = default)
{
    return Task.Run(
        () =>
        {
            _model = new Model(modelDir);
            _tokenizer = new Tokenizer(_model);
        },
        cancellationToken);
}
```

**To Reproduce**
1. Run the app on the debugger and go to **Generate Text**.
2. Download a model if you don't have any, restart the app then go to **Generate Text** again.
3. Close the app while the progress ring is in progress.

**Expected behavior**
The app should close without any errors.

**Screenshots**

![Image](https://github.com/user-attachments/assets/df09a25d-536c-4fbc-8e9f-d265a1f8e5ff)

**Please complete the following information:**
 - App Version [e.g. 0.4.1 from the Microsoft Store]:

**Additional context**
This might be the same for other models.

**Comment by nmetulev** [comment]
We likely need to capture the close event and wait for the sample to clean up resources. @azchohfi ideas?

**Comment by azchohfi** [comment]
Yes, that is pretty much it. Working on a PR.
