### ISSUE TITLE
[FEATURE] GPU memory warning looks a bit too "cut-off"

### ISSUE THREAD

**Issue by BobLd** [microsoft/ai-dev-gallery#47]
**Is your feature request related to a problem? Please describe.**
The GPU memory warning looks a bit too "cut-off". My GPU is seen to have 7.8GB instead of 8GB which prevents me to install Phi 3 Medium for GPU. See below:

![Image](https://github.com/user-attachments/assets/c5e4682a-970a-4b7e-84ed-820bf8d51cc9)

**Describe the solution you'd like**
I guess rounding the memory measure with 0 decimal place would do the trick here.

**Describe alternatives you've considered**
An alternative would be to have an "Install anyway" option.

**Comment by insomniachi** [comment]
probably has to do with using 1000MB = 1GB or 1024MB = 1GB.
i'm guessing you get 7.8 because (8000 / 1024) = 7.8125

**Comment by BobLd** [comment]
Makes a lot of sense indeed!

**Comment by nmetulev** [comment]
You can modify the compatibility checker code if you'd like to ignore the compatibility check and download the model anyway https://github.com/microsoft/ai-dev-gallery/blob/main/AIDevGallery/Models/ModelCompatibility.cs#L36

If you do this and you find Phi Medium works ok on your machine, please let us know and we can consider updating the requirements. In the meantime, I'll close this issue as "works as expected"
