### ISSUE TITLE
[FEATURE] Use file-scoped namespaces on the entire project

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/ai-dev-gallery#52]
**Is your feature request related to a problem? Please describe.**
Now that samples are using file-scoped namespace (#28), it's better to apply it to the entire project to keep consistency and also improve readability.

**Describe the solution you'd like**
- [x] Update **editor.config** to prefer file-scoped namespaces and issue warnings for block-scoped namespaces.
- [x] Convert all *.cs files to file-scoped namespaces.
- [x] Add .git-blame-ignore-revs file.
- [ ] After merging, update the commit id on .git-blame-ignore-revs.

**Comment by AndrewKeepCoding** [comment]
I'd be happy to create a PR for this.

**Comment by nmetulev** [comment]
Sounds like a good improvement, feel free to work on it
