### ISSUE TITLE
[BUG] The export button fails

### ISSUE THREAD

**Issue by emiliosanchis** [microsoft/ai-dev-gallery#53]
**Describe the bug**
The export button fails with the following exception

**To Reproduce**
1. Go to 'any of the examples'
2. Click on 'Export button'
3. Exception error on line 416 of [ScenarioPage.xaml.cs](https://github.com/microsoft/ai-dev-gallery/blob/main/AIDevGallery/Pages/ScenarioPage.xaml.cs) when executing line 365 var folder = await picker.PickSingleFolderAsync(); 
4. See error: 
  ```
System.Runtime.InteropServices.COMException
  HResult=0x80004005
  Mensaje = Error no especificado

La propiedad FileTypeFilters tiene que tener especificado al menos un filtro de tipo de archivo.
  Origen = WinRT.Runtime
  Seguimiento de la pila:
   en WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   en ABI.Windows.Storage.Pickers.IFolderPickerMethods.PickSingleFolderAsync(IObjectReference _obj)
   en Windows.Storage.Pickers.FolderPicker.PickSingleFolderAsync()
   en AIDevGallery.Pages.ScenarioPage.<ExportSampleToggle_Click>d__13.MoveNext() en f:\Descargas\ai-dev-gallery-main\ai-dev-gallery-main\AIDevGallery\Pages\ScenarioPage.xaml.cs: línea 365

  Esta excepción se generó originalmente en esta pila de llamadas:
    [Código externo]
    AIDevGallery.Pages.ScenarioPage.ExportSampleToggle_Click(object, Microsoft.UI.Xaml.RoutedEventArgs) en ScenarioPage.xaml.cs
System.Runtime.InteropServices.COMException (0x80004005): Error no especificado
```

5. Github Copilot suggestion:  Add the following line: picker.FileTypeFilter.Add("*");
6. Applying Copilot's suggestion works correctly

**Comment by nmetulev** [comment]
I'm unable to repro this, but the suggested resolution sounds like a good improvement anyway. @emiliosanchis, do you want to submit a PR adding the line?

**Comment by emiliosanchis** [comment]
I have verified that in Windows 11 it does not give the error, it only gives the error in Windows 10
